/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExamCell;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tanay Thakar
 */
public class BranchSemesterExamReport extends javax.swing.JFrame {

    /**
     * Creates new form BranchSemesterExamReport
     */
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public BranchSemesterExamReport() {
        initComponents();
        conn = db.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Branch - Semester Exam Report");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        jLabel1.setText("Branch - Semester Exam Report");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an Option", "Biomedical", "Biotechnology", "Chemical", "Civil", "Computer", "Electronics & Telecommunication", "Electrical", "Information Technology", "Mechanical" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Branch :");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Semester :");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Reports/Report Icon.png"))); // NOI18N
        jButton2.setText("Generate Report");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(21, 21, 21)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        setSize(new java.awt.Dimension(628, 401));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String branch = this.jComboBox2.getSelectedItem().toString();
        String sem = this.jComboBox1.getSelectedItem().toString();

        JFileChooser saveDialog = new JFileChooser();
        saveDialog.setSelectedFile(new File(branch+" - "+sem+" Sem Exam Report.pdf"));
        int dialogResult = saveDialog.showSaveDialog(null);
        String filePath = saveDialog.getSelectedFile().getPath();
        if(dialogResult == 0)
        {
            int i = 1;
            
            try
            {
                Document myDoc = new Document(PageSize.A4.rotate());
                PdfWriter myWriter = PdfWriter.getInstance(myDoc, new FileOutputStream(filePath));
                PdfPTable Table1 = new PdfPTable(2);
                
                myDoc.open();
                float[] column = new float[] {5,5};
                Table1.setWidths(column);
                Table1.setWidthPercentage(80);
                
                myDoc.add(new Paragraph("                                                        Mahatma Gandhi Mission's",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                myDoc.add(new Paragraph("                                        College of Engineering & Technolgy, Kamothe",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                myDoc.add(new Paragraph("       "));
                myDoc.add(new Paragraph("                                                                    Branch - Semester Exam Report",FontFactory.getFont(FontFactory.HELVETICA,15,Font.BOLD)));
                myDoc.add(new Paragraph("       "));
                Table1.addCell(new PdfPCell(new Paragraph("Branch :    "+branch,FontFactory.getFont(FontFactory.TIMES_BOLD,13,Font.PLAIN)))).setBorderWidth(0);
                Table1.addCell(new PdfPCell(new Paragraph("Semester :    "+sem,FontFactory.getFont(FontFactory.TIMES_BOLD,13,Font.PLAIN)))).setBorderWidth(0);
                myDoc.add(Table1);
                myDoc.add(new Paragraph("           "));
                
                if(sem.equals("ALL"))
                {
                    PdfPTable Table = new PdfPTable(9);
                    float[] columnWidths = new float[] {3,4,3,4,5,6,11,5,5};
                    Table.setWidths(columnWidths);
                    Table.setWidthPercentage(100);
                    
                    String query = "select Semester, Slot, Date, Day, Time, Subject_Name, Subject_Code, Scheme from Exam_TimeTable where Branch = '"+branch+"' order by Semester and Date";
                    pst=conn.prepareStatement(query);
                    rs=pst.executeQuery();
                    
                    Table.addCell(new PdfPCell(new Paragraph("   Sr. No.",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("    Semester",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("     Slot",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("       Date",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("            Day",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("            Time",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("                             Paper",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("    Paper Code",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("        Scheme",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.completeRow();
                    Table.setHorizontalAlignment(Element.ALIGN_CENTER);
                    
                    while(rs.next())
                    {
                        Table.addCell(new PdfPCell(new Paragraph("         "+i+"",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("             "+rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("         "+rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(5),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(6),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(7),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(8),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.completeRow();
                        i++;
                    }

                    Table.setHorizontalAlignment(Element.ALIGN_CENTER);
                    myDoc.add(Table);
                    
                }
                else
                {
                    PdfPTable Table = new PdfPTable(8);
                    float[] columnWidths = new float[] {3,3,4,5,6,11,5,5};
                    Table.setWidths(columnWidths);
                    Table.setWidthPercentage(100);
                    
                    String query = "select Slot, Date, Day, Time, Subject_Name, Subject_Code, Scheme from Exam_TimeTable where Branch = '"+branch+"' and Semester = '"+sem+"' order by Date";
                    pst=conn.prepareStatement(query);
                    rs=pst.executeQuery();
                    
                    Table.addCell(new PdfPCell(new Paragraph("   Sr. No.",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("      Slot",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("        Date",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("            Day",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("               Time",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("                                Paper",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("      Paper Code",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.addCell(new PdfPCell(new Paragraph("          Scheme",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                    Table.completeRow();
                    Table.setHorizontalAlignment(Element.ALIGN_CENTER);
                    
                    while(rs.next())
                    {
                        Table.addCell(new PdfPCell(new Paragraph("       "+i+"",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("          "+rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(5),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(6),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("     "+rs.getString(7),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.completeRow();
                        i++;
                    }

                    Table.setHorizontalAlignment(Element.ALIGN_CENTER);
                    myDoc.add(Table);
                }
                
                myDoc.close();

                JOptionPane.showMessageDialog(null,"Branch - Semester Exam Report Successfully Generated\n    \nFile Location : "+filePath);
            
            }
            catch(DocumentException | HeadlessException | FileNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(null,e,"ERROR",JOptionPane.ERROR_MESSAGE);
            }
            finally
            {

                try {
                    rs.close();
                    pst.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchSemesterExamReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchSemesterExamReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchSemesterExamReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchSemesterExamReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BranchSemesterExamReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
