/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExamCell;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tanay Thakar
 */
public class DailyAllocationSheet extends javax.swing.JFrame {

    /**
     * Creates new form DailyAllocationSheet
     */
    
    Connection conn = null;
    ResultSet rs,rs1 = null;
    PreparedStatement pst,pst1 = null;
    
    public DailyAllocationSheet() {
        initComponents();
        conn = db.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Daily Allocation Sheet");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel1.setText("Daily Allocation Sheet");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Reports/Report Icon.png"))); // NOI18N
        jButton2.setText("Generate Report");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Date :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        setSize(new java.awt.Dimension(597, 346));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        DateFormat df = new SimpleDateFormat("EEEE");
        DateFormat df1 = new SimpleDateFormat("MMM dd,yyyy");
        
        String day = df.format(this.jDateChooser1.getDate());
        String date = df1.format(jDateChooser1.getDate());
        
        JFileChooser saveDialog = new JFileChooser();
        saveDialog.setSelectedFile(new File(date+" - Exam Duty Report.pdf"));
        int dialogResult = saveDialog.showSaveDialog(null);
        String filePath = saveDialog.getSelectedFile().getPath();
        if(dialogResult == 0)
        {
            try
            {
                int i = 1;

                Document myDoc = new Document(PageSize.A4.rotate());
                PdfWriter myWriter = PdfWriter.getInstance(myDoc, new FileOutputStream(filePath));
                PdfPTable Table1 = new PdfPTable(2);
                PdfPTable Table = new PdfPTable(9);
                myDoc.setMargins(28, 28, 28, 28);
                myDoc.open();

                float[] column = new float[] {5,5};
                Table1.setWidths(column);
                Table1.setWidthPercentage(85);

                float[] columnWidths = new float[] {3,2.5f,5.5f,9.5f,3.5f,4.5f,11,3.5f,9};
                Table.setWidths(columnWidths);
                Table.setWidthPercentage(100);

                myDoc.add(new Paragraph("                                                        Mahatma Gandhi Mission's",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                myDoc.add(new Paragraph("                                        College of Engineering & Technolgy, Kamothe",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                myDoc.add(new Paragraph("       "));
                myDoc.add(new Paragraph("                                                                               Daily Allocation Sheet",FontFactory.getFont(FontFactory.HELVETICA,15,Font.BOLD)));
                myDoc.add(new Paragraph("       "));
                Table1.addCell(new PdfPCell(new Paragraph("Date :     "+date,FontFactory.getFont(FontFactory.TIMES_BOLD,13,Font.PLAIN)))).setBorderWidth(0);
                Table1.addCell(new PdfPCell(new Paragraph("Day :     "+day,FontFactory.getFont(FontFactory.TIMES_BOLD,13,Font.PLAIN)))).setBorderWidth(0);
                myDoc.add(Table1);
                myDoc.add(new Paragraph("           "));
            
                Table.addCell(new PdfPCell(new Paragraph(" Sr. No.",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                Table.addCell(new PdfPCell(new Paragraph("   Slot",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                Table.addCell(new PdfPCell(new Paragraph("           Time",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                Table.addCell(new PdfPCell(new Paragraph("                  Branch",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                Table.addCell(new PdfPCell(new Paragraph(" Semester",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                Table.addCell(new PdfPCell(new Paragraph("  Paper Code",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                Table.addCell(new PdfPCell(new Paragraph("                        Paper ",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                Table.addCell(new PdfPCell(new Paragraph("  Scheme",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                Table.addCell(new PdfPCell(new Paragraph("             Invigilator",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                Table.completeRow();
                Table.setHorizontalAlignment(Element.ALIGN_CENTER);
                
                String query = "Select Subject_Code,Name from Duty_Details where Duty_Date = '"+date+"' order by Duty_Slot desc";
                String sql = "Select * from Exam_TimeTable where Subject_Code = ?";
                String abc;
                pst=conn.prepareStatement(query);
                rs=pst.executeQuery();
                
                while(rs.next())
                {
                    pst1=conn.prepareStatement(sql);
                    abc = rs.getString(1);
                    pst1.setString(1, abc);
                    rs1=pst1.executeQuery();
                    while(rs1.next())
                    {
                        Table.addCell(new PdfPCell(new Paragraph("      "+i+"",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("      "+rs1.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("  "+rs1.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("  "+rs1.getString(7),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("          "+rs1.getString(8),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("        "+rs1.getString(5),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("  "+rs1.getString(6),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("  "+rs1.getString(9),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.addCell(new PdfPCell(new Paragraph("  "+rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                        Table.completeRow();
                        i++;
                    
                    }
                    
                }

                Table.setHorizontalAlignment(Element.ALIGN_CENTER);

                myDoc.add(Table);
                
                myDoc.close();

                JOptionPane.showMessageDialog(null,"Daily Exam Duty Allocation Sheet Successfully Generated\n    \nFile Location : "+filePath);
                
                this.dispose();
            }
            catch(DocumentException | HeadlessException | FileNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(null,e,"ERROR",JOptionPane.ERROR_MESSAGE);
            }
            finally
            {
                try {
                    rs.close();
                    rs1.close();
                    pst.close();
                    pst1.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DailyAllocationSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DailyAllocationSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DailyAllocationSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DailyAllocationSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DailyAllocationSheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
