/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExamCell;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.TabStop;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tanay Thakar
 */
public class SheetMenu extends javax.swing.JFrame {

    /**
     * Creates new form SheetMenu
     */
    Connection conn = null;
    ResultSet rs,rs1 = null;
    PreparedStatement pst,pst1 = null;
    java.util.Date date;
    java.sql.Date sqldate;
    int rowCounted;
    
    public SheetMenu() {
        initComponents();
        conn = db.connect();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        jButton8.setText("jButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sheet Generator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setText("Exam Duty Allocation Overview Sheet");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.white));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton3.setText("Faculty Wise Exam Duty Sheet");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.white));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton4.setText("Faculty - Exam Duty Sheet");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.white));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton5.setText("Daily Allocation Sheet");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.white));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton6.setText("Branch - Semester Exam Duty Sheet");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.white));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton7.setText("Block Details");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.white));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton9.setText("Exam Schedule");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.white));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton10.setText("Employee Details");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.white));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel16.setText("Reports Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel16)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        setSize(new java.awt.Dimension(810, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FacultyExamDutySheet feds = new FacultyExamDutySheet();
        feds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        this.dispose();
        
        JFileChooser saveDialog = new JFileChooser();
        saveDialog.setSelectedFile(new File("Employee Details.pdf"));
        int dialogResult = saveDialog.showSaveDialog(null);
        String filePath = saveDialog.getSelectedFile().getPath();
        if(dialogResult == 0)
        {
        try
        {
            String sql = "select * from Faculty_Details group by Branch order by Designation";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();      
            
            int i =1;
            
            Document myDoc = new Document();
            
            PdfWriter myWriter = PdfWriter.getInstance(myDoc, new FileOutputStream(filePath));
            PdfPTable Table = new PdfPTable(5);
            myDoc.open();
            
            float[] columnWidths = new float[] {2,3,6,7,4};
            Table.setWidths(columnWidths);
            Table.setWidthPercentage(100);
            
            myDoc.add(new Paragraph("                            Mahatma Gandhi Mission's",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
            myDoc.add(new Paragraph("             College of Engineering & Technolgy, Kamothe",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
            myDoc.add(new Paragraph("       "));
            myDoc.add(new Paragraph("                                            Employee Details Report",FontFactory.getFont(FontFactory.HELVETICA,15,Font.BOLD)));
            myDoc.add(new Paragraph("       "));
//            myDoc.add(new Paragraph("------------------------------------------------------------------------------------------------------------------------"));
//            myDoc.add(new Paragraph("       "));
            Table.addCell(new PdfPCell(new Paragraph("  Sr. No.",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("        UID",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("                    Name",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("                        Branch",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("      Designation",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.completeRow();
            Table.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            
            while(rs.next())
            {
                Table.addCell(new PdfPCell(new Paragraph("        "+i+"",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("    "+rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("  "+rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("  "+rs.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("  "+rs.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.completeRow();
                i++;
            }
            
            Table.setHorizontalAlignment(Element.ALIGN_CENTER);
            myDoc.add(Table);
//            myDoc.add(new Paragraph("       "));
//            myDoc.add(new Paragraph("------------------------------------------------------------------------------------------------------------------------"));
            myDoc.close();
            
            JOptionPane.showMessageDialog(null,"Employee Details Report Successfully Generated\n    \nFile Location : "+filePath);
        }
        catch(DocumentException | HeadlessException | FileNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e,"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        finally
        {
            
            try {
                rs.close();
                pst.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        this.dispose();
        
        JFileChooser saveDialog = new JFileChooser();
        saveDialog.setSelectedFile(new File("Exam Schedule.pdf"));
        int dialogResult = saveDialog.showSaveDialog(null);
        String filePath = saveDialog.getSelectedFile().getPath();
        if(dialogResult == 0)
        {
        try
        {
            String sql = "select * from Exam_TimeTable order by Date";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();      
            
            int i =1;
            
            Document myDoc = new Document(PageSize.A4.rotate());
            PdfWriter myWriter = PdfWriter.getInstance(myDoc, new FileOutputStream(filePath));
            PdfPTable Table = new PdfPTable(10);
            myDoc.setMargins(28, 28, 28, 28);
            myDoc.open();
            
            float[] columnWidths = new float[] {3,4,4,7,3,5,11,10,4,3.5f};
            Table.setWidths(columnWidths);
            Table.setWidthPercentage(100);
            
                        
            myDoc.add(new Paragraph("                                                        Mahatma Gandhi Mission's",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
            myDoc.add(new Paragraph("                                        College of Engineering & Technolgy, Kamothe",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
            myDoc.add(new Paragraph("       "));
            myDoc.add(new Paragraph("                                                                            Exam Schedule Report",FontFactory.getFont(FontFactory.HELVETICA,15,Font.BOLD)));
            myDoc.add(new Paragraph("       "));
//            myDoc.add(new Paragraph("------------------------------------------------------------------------------------------------------------------------"));
//            myDoc.add(new Paragraph("       "));
            Table.addCell(new PdfPCell(new Paragraph(" Sr. No.",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("     Date",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("      Day",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("             Time",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("    Slot",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("  Paper Code",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("              Paper Title",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("                  Branch",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("  Semester",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("  Scheme",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            
            Table.completeRow();
            Table.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            
            while(rs.next())
            {
                Table.addCell(new PdfPCell(new Paragraph("      "+i+"",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("  "+rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("  "+rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("  "+rs.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("       "+rs.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("  "+rs.getString(5),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("  "+rs.getString(6),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("  "+rs.getString(7),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("           "+rs.getString(8),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("   "+rs.getString(9),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.completeRow();
                i++;
            }
            
            Table.setHorizontalAlignment(Element.ALIGN_CENTER);
            myDoc.add(Table);
//            myDoc.add(new Paragraph("       "));
//            myDoc.add(new Paragraph("------------------------------------------------------------------------------------------------------------------------"));
            myDoc.close();
            
            JOptionPane.showMessageDialog(null,"Exam Schedule Report Successfully Generated\n\nFile Location : "+filePath);
        }
        catch(DocumentException | HeadlessException | FileNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e,"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        finally
        {
            
            try {
                rs.close();
                pst.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        this.dispose();
        
        JFileChooser saveDialog = new JFileChooser();
        saveDialog.setSelectedFile(new File("Block Details.pdf"));
        int dialogResult = saveDialog.showSaveDialog(null);
        String filePath = saveDialog.getSelectedFile().getPath();
        
        if(dialogResult == 0)
        {
        try
        {
            String sql = "select * from Block_Details order by Floor";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();      
            
            int i =1;
            
            Document myDoc = new Document();
            PdfWriter myWriter = PdfWriter.getInstance(myDoc, new FileOutputStream(filePath));
            PdfPTable Table = new PdfPTable(4);
            myDoc.open();
            
            float[] columnWidths = new float[] {5,5,5,5};
            Table.setWidths(columnWidths);
            Table.setWidthPercentage(100);
            
            myDoc.add(new Paragraph("                            Mahatma Gandhi Mission's",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
            myDoc.add(new Paragraph("             College of Engineering & Technolgy, Kamothe",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
            myDoc.add(new Paragraph("       "));
            myDoc.add(new Paragraph("                                                Block Details Report",FontFactory.getFont(FontFactory.HELVETICA,15,Font.BOLD)));
            myDoc.add(new Paragraph("       "));
//            myDoc.add(new Paragraph("------------------------------------------------------------------------------------------------------------------------"));
//            myDoc.add(new Paragraph("       "));
            Table.addCell(new PdfPCell(new Paragraph("                 Sr. No.",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("               Block No.",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("                 Floor",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
            Table.addCell(new PdfPCell(new Paragraph("               Capacity",FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.BOLD)))).setBorderWidth(1);
                        
            Table.completeRow();
            Table.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            
            while(rs.next())
            {
                Table.addCell(new PdfPCell(new Paragraph("                           "+i+"",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("                      "+rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("                          "+rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                Table.addCell(new PdfPCell(new Paragraph("                         "+rs.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                
                Table.completeRow();
                i++;
            }
            
            Table.setHorizontalAlignment(Element.ALIGN_CENTER);
            myDoc.add(Table);
//            myDoc.add(new Paragraph("       "));
//            myDoc.add(new Paragraph("------------------------------------------------------------------------------------------------------------------------"));
            myDoc.close();
            
            JOptionPane.showMessageDialog(null,"Block Details Report Successfully Generated\n\nFile Location : "+filePath);
        }
        catch(DocumentException | HeadlessException | FileNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e,"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        finally
        {
            
            try {
                rs.close();
                pst.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FacultyWiseExamDutySheet fweds = new FacultyWiseExamDutySheet();
        fweds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        BranchSemesterExamReport bser = new BranchSemesterExamReport();
        bser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DailyAllocationSheet das = new DailyAllocationSheet();
        das.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        
        JFileChooser saveDialog = new JFileChooser();
        saveDialog.setSelectedFile(new File("Exam Duty Allocation Overview Sheet.pdf"));
        int dialogResult = saveDialog.showSaveDialog(null);
        String filePath = saveDialog.getSelectedFile().getPath();
        if(dialogResult == 0)
        {
            try
            {
                String sql = "select distinct Name from Duty_Details order by Duty_Date";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();    
                         
                int i =1;
            
                Document myDoc = new Document(PageSize.A4.rotate());
                PdfWriter myWriter = PdfWriter.getInstance(myDoc, new FileOutputStream(filePath));
                PdfPTable Table = new PdfPTable(17);
                myDoc.setMargins(12, 12, 28, 28);
                myDoc.open();
            
                float[] columnWidths = new float[] {1,6,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3};
                Table.setWidths(columnWidths);
                Table.setWidthPercentage(100);
            
                        
                myDoc.add(new Paragraph("                                                        Mahatma Gandhi Mission's",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                myDoc.add(new Paragraph("                                        College of Engineering & Technolgy, Kamothe",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                myDoc.add(new Paragraph("       "));
                myDoc.add(new Paragraph("                                                                Exam Duty Allocation Overview Sheet",FontFactory.getFont(FontFactory.HELVETICA,15,Font.BOLD)));
                myDoc.add(new Paragraph("       "));
//            myDoc.add(new Paragraph("------------------------------------------------------------------------------------------------------------------------"));
//            myDoc.add(new Paragraph("       "));
                
                Table.setHorizontalAlignment(Element.ALIGN_CENTER);
            
                while(rs.next())
                {
                    String sql1 = "select Duty_Date, Duty_Slot from Duty_Details where Name = '"+rs.getString(1)+"'";
                    pst1 = conn.prepareStatement(sql1);
                    rs1 = pst1.executeQuery();
                    
                    Table.addCell(new PdfPCell(new Paragraph(""+i+"",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                    Table.addCell(new PdfPCell(new Paragraph(" "+rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
                    
                    while(rs1.next())
                        Table.addCell(new PdfPCell(new Paragraph(rs1.getString(1)+" - "+rs1.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.PLAIN))));              
                        
                    Table.completeRow();
                    i++;
                }
            
                Table.setHorizontalAlignment(Element.ALIGN_CENTER);
                myDoc.add(Table);
//            myDoc.add(new Paragraph("       "));
//            myDoc.add(new Paragraph("------------------------------------------------------------------------------------------------------------------------"));
                myDoc.close();
            
                JOptionPane.showMessageDialog(null,"Exam Duty Allocation Overview Sheet Successfully Generated\n\nFile Location : "+filePath);
            }
            catch(DocumentException | HeadlessException | FileNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(null,e,"ERROR",JOptionPane.ERROR_MESSAGE);
            }
            finally
            { 
                try 
                {
                    rs.close();
                    rs1.close();
                    pst.close();
                    pst1.close();
                } 
                catch (SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SheetMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SheetMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SheetMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SheetMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SheetMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel16;
    // End of variables declaration//GEN-END:variables
}
